### ISSUE TITLE
youtube titles not working

### ISSUE THREAD

**Issue by kylealwyn** [microlinkhq/support#46]
<img width="895" alt="CleanShot 2023-01-03 at 23 33 30@2x" src="https://user-images.githubusercontent.com/14184138/210505501-97458875-3e15-4c00-9c72-d4cfa50d2a4d.png">

also the input box when testing urls is quite small

**Comment by Kikobeats** [comment]
Thanks for reporting; working into resolve it 🙂

**Comment by Kikobeats** [comment]
Hello, this is now fixed.

The issue was related with the fact the service is sending too much traffic to YouTube servers, and YouTube servers were rate limiting us.

What we did is to did a good traffic distribution across our origin servers to prevent this. Also, we take this an opportunity for improving [YouTube 
 metadata rules](https://github.com/microlinkhq/metascraper/pull/618).

Unfortunately, this is just guaranteed for the paid plan. Note the website is using the free plan (although it should be work better now since we are sending less traffic using the same origin)
